// lib/metrics.ts
import client from "prom-client"

const register = new client.Registry()

// Prevent duplicate metric registration on hot reload
if (!globalThis.promRegistry) {
  client.collectDefaultMetrics({ register })
  globalThis.promRegistry = register
}

export const routesGenerated = new client.Counter({
  name: "routes_generated_total",
  help: "Total routes generated by users",
})

register.registerMetric(routesGenerated)

export default globalThis.promRegistry as client.Registry
